name: Rotate Personal Access Token

on:
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight UTC

jobs:
  rotate-token:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Rotate Token
        run: |
          # Generate a new personal access token
          NEW_TOKEN=$(gh auth refresh-token --scopes repo,user)

          # Update the token in GitHub settings using GitHub API
          curl -X PATCH \
            -H "Authorization: token $GITHUB_TOKEN" \
            -d '{"token": "'"$NEW_TOKEN"'"}' \
            https://api.github.com/user/token

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
