name: Change SSH Key

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC

jobs:
  change_ssh_key:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Retrieve Current SSH Keys
        id: get_keys
        run: |
          keys=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/user/keys)
          echo "::set-output name=keys::$keys"

      - name: Delete Old SSH Key (optional)
        if: steps.get_keys.outputs.keys != ''
        run: |
          # Replace OLD_KEY_ID with the ID of the SSH key you want to delete
          curl -X DELETE -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/user/keys/OLD_KEY_ID

      - name: Add New SSH Key
        run: |
          # Replace NEW_SSH_KEY with the content of your new SSH key and TITLE with a descriptive title
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -d '{"title":"TITLE","key":"NEW_SSH_KEY"}' https://api.github.com/user/keys
