name: Pull Request Validation

on:
  pull_request:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update dependencies
        run: |
          # Replace this with the command to update dependencies
          npm install -g npm-check-updates
          ncu -u
          npm install
          git commit -am "chore: Update dependencies" && git push
