name: Scan Pull Requests
on:
 pull_request:
    types: [opened, synchronize]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm install --save-dev snyk
      - run: npx synk auth
      - run: npx snyk test
