name: Pull Request Validation

on:
  pull_request:
    branches:
      - main

jobs:
  scan_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Validate Pull Request
        run: |
          # Get the list of changed files in the pull request
          if [ "$(git rev-parse HEAD)" = "$(git rev-list --max-parents=0 HEAD)" ]; then
            echo "This is the initial commit. No validation checks needed."
            exit 0
          fi

          changed_files=$(git diff --name-only HEAD^)

          # Perform validation checks on each changed file
          for file in $changed_files; do
            # Check if the file contains any forbidden patterns
            if grep -q "forbidden_pattern" $file; then
              echo "Error: File $file contains forbidden pattern."
              exit 1
            fi

            # Add more custom validation checks as needed...
          done
